% Piper PA-28-151, 1974
% Ser. no. 28-7415455
% N-Number: 121PW

% Fuel Systems
% 2 x 24g tanks (48g useable fuel)
% 8g/h cruise consumption

% Flaps
\newcommand{\flapsfirstnotch}[0]{$10\degree$}
\newcommand{\flapssecondnotch}[0]{$25\degree$}
\newcommand{\flapsthirdnotch}[0]{$40\degree$}

% Various V_speeds
\newcommand{\vfe}[0]{$109$}
\newcommand{\vr}[0]{$60$}
\newcommand{\vy}[0]{$76$}
\newcommand{\vx}[0]{$66$}
\newcommand{\vg}[0]{$69$}
\newcommand{\vszero}[0]{$50$}
\newcommand{\vsone}[0]{$56$}
